image: andthensome/docker-node-rsync

pipelines:
  branches:
    master: 
      - step:
          name: Build Package
          script:
          - npm install
          - npm run build -- --production
      - step:
          name: Deploy Package
          image: mwienk/docker-git-ftp
          script:
          - ls
          - sftp $DEV_DEPLOY_URL <<< ../$PACKAGE_DIR
            