image: andthensome/docker-node-rsync

pipelines:
  branches:
    master: 
      - step:
          name: Build Package
          script:
          - npm install
          - npm run build -- --production
          - apk add --no-cache lftp
          - lftp -u $DEV_DEPLOY_URL >>> $'rm -rf '$PACKAGE_DIR'/*'
          - scp -r ../$PACKAGE_DIR $DEV_DEPLOY_URL
          
            