image: andthensome/docker-node-rsync
pipelines:
  branches:
    develop:
      - step:
          caches:
          - node
          script:
          - npm install
          - npm run build
          - rsync -clvrz ../$PACKAGE_DIR $DEV_DEPLOY_URL
