image: andthensome/docker-node-rsync

pipelines:
  branches:
    master: 
      - step:
          name: Build Package
          script:
          - npm install
          - npm run build -- --production
      - step:
          image: atmoz/sftp
          name: Deploy Package
          script:
            - -v $DEV_DEPLOY_URL:../$PACKAGE_DIR \
            - -p 2222:22 -d atmoz/sftp \
            - $SSH_USER:1001