image: andthensome/docker-node-rsync

pipelines:
  branches:
    master: 
      - step:
          name: Build Package
          script:
          - npm install
          - npm run build -- --production
          - sftp $DEV_DEPLOY_URL <<< $'rm '$PACKAGE_DIR'/**/*' <<< $'rmdir '$PACKAGE_DIR'/**/*'
          - scp -r ../$PACKAGE_DIR $DEV_DEPLOY_URL
          
            