image: andthensome/docker-node-rsync

pipelines:
  branches:
    master: 
      - step:
          name: Build Package
          script:
          - npm install
          - npm run build -- --production
          - scp ../$PACKAGE_DIR/ $DEV_DEPLOY_URL
          #artifacts: 
          #- ../$PACKAGE_DIR/**
      #- step:
       #   name: Deploy Package
        #  image: quay.io/aptible/sftp
         # script:
          #- cd ..
          #- ls
          
            