image: andthensome/docker-node-rsync

pipelines:
  branches:
    master: 
      - step:
          name: Build Package
          script:
          - npm install
          - npm run build -- --production
          artifacts: 
          - ../$PACKAGE_DIR
      - step:
          name: Deploy Package
          image: quay.io/aptible/sftp
          script:
          - ls
          - cd ..
          - ls
          - sftp $DEV_DEPLOY_URL
          - sftp> put $PACKAGE_DIR/
            