image: andthensome/docker-node-rsync
options:
  docker: true

pipelines:
  branches:
    master: 
      - step:
          name: Build Package
          script:
          - npm install
          - npm run build -- --production
      - step:
          image: atmoz/sftp
          name: Deploy Package
          script:
            - docker run \
              -v $DEV_DEPLOY_URL:../$PACKAGE_DIR \
              -p 2222:22 -d atmoz/sftp \
              $SSH_USER:1001